version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: yii2_app
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      #- ./.env:/var/www/backend/.env
    depends_on:
      - db
    networks:
      - appnet
    user: "${UID}:${GID}"
    env_file:
      - .env

  nuxt:
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
    container_name: nuxt_app
    working_dir: /app
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
    command: yarn dev
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8083:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/backend
      #- ./frontend:/app
    depends_on:
      - php
      #- nuxt
    networks:
      - appnet

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

networks:
  appnet:

volumes:
  pgdata:
